export const APP_TEXTS = {
  GREETING: 'Good afternoon, Alessandra!',
  SEARCH_RECIPES: 'Search recipes',
  TRENDING_NOW: 'Trending now 🔥',
  POPULAR_CATEGORY: 'Popular category',
  NO_ITEMS: 'No items available',
  TIME: 'Time',
  STATIC_TIME: '10 Mins',
  SAVED_RECIPES: 'Saved recipes',
  INGREDIENTS: 'Ingredients',
  ITEMS: 'items',
  CREATE_RECIPE: 'Create recipe',
  NOTIFICATIONS: 'Notifications',
  TODAY: 'Today',
  NEW_RECIPE: 'New recipe!',
  RANDOM_RECIPE: 'Tap to see a random recipe.',
};
