export enum INGREDIENT_KEYS {
  ITEM_1 = 'strIngredient1',
  ITEM_2 = 'strIngredient2',
  ITEM_3 = 'strIngredient3',
  ITEM_4 = 'strIngredient4',
  ITEM_5 = 'strIngredient5',
  ITEM_6 = 'strIngredient6',
  ITEM_7 = 'strIngredient7',
  ITEM_8 = 'strIngredient8',
  ITEM_9 = 'strIngredient9',
  ITEM_10 = 'strIngredient10',
  ITEM_11 = 'strIngredient11',
  ITEM_12 = 'strIngredient12',
  ITEM_13 = 'strIngredient13',
  ITEM_14 = 'strIngredient14',
  ITEM_15 = 'strIngredient15',
  ITEM_16 = 'strIngredient16',
  ITEM_17 = 'strIngredient17',
  ITEM_18 = 'strIngredient18',
  ITEM_19 = 'strIngredient19',
  ITEM_20 = 'strIngredient20',
}
