export enum REACT_QUERY_KEYS {
  TRENDING_RECIPES = 'TRENDING_RECIPES',
  ALL_CATEGORIES = 'ALL_CATEGORIES',
  RECIPES_IN_CATEGORY = 'RECIPES_IN_CATEGORY',
  RECIPE_DETAILS = 'RECIPE_DETAILS',
  RANDOM_RECIPE = 'RANDOM_RECIPE',
}
