export enum ROUTE_NAMES {
  HOME = 'HOME',
  SAVED_RECIPES = 'SAVED_RECIPES',
  CREATE_RECIPE = 'CREATE_RECIPE',
  NOTIFICATIONS = 'NOTIFICATIONS',
  MY_PROFILE = 'MY_PROFILE',
  HOME_STACK = 'HOME_STACK',
  RECIPE_DETAILS_STACK = 'RECIPE_DETAILS_STACK',
  CREATE_RECIPE_STACK = 'CREATE_RECIPE_STACK',
}
