export const ROUTE_NAMES = {
  HOME: 'HOME',
  SAVED_RECIPES: 'SAVED_RECIPES',
  CREATE_RECIPE: 'CREATE_RECIPE',
  NOTIFICATIONS: 'NOTIFICATIONS',
  MY_PROFILE: 'MY_PROFILE',
  SAVED_RECIPES_STACK: 'SAVED_RECIPES_STACK',
  RECIPE_DETAIL_STACK: 'RECIPE_DETAIL_STACK',
};
